version: "3.9"

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: portfolio-reactified-nginx
    restart: unless-stopped
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - portfolio-reactified-backend

  portfolio-reactified-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: bash /code/docker-entrypoint.prod.sh
    container_name: portfolio-reactified-backend
    image: portfolio-reactified-backend
    volumes:
      - ../portfolio-reactified-backend-logs:/logs
      - static_volume:/code/static
      - media_volume:/code/media
      - nginx_secrets:/etc/letsencrypt
    ports:
      - 8000:8000
    env_file: .env
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

volumes:
  static_volume:
  media_volume:
  nginx_secrets:
