services:

  portfolio-reactified-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: bash /code/docker-entrypoint.prod.sh
    container_name: portfolio-reactified-backend
    image: portfolio-reactified-backend
    volumes:
      - ../portfolio-reactified-backend-logs:/logs
      - static_volume:/code/static
      - media_volume:/code/media
      - nginx_secrets:/etc/letsencrypt
    ports:
      - 8000:8000
    env_file: .env
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - app-network

volumes:
  static_volume:
  media_volume:
  nginx_secrets:

networks:
  app-network:
