version: "3.9"

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: django-react-nginx
    restart: unless-stopped
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - django-react-backend

  django-react-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: bash /code/docker-entrypoint.prod.sh
    container_name: django-react-backend
    image: django-react-backend
    volumes:
      - ../django-react-backend-logs:/logs
      - static_volume:/code/static
      - media_volume:/code/media
      - nginx_secrets:/etc/letsencrypt
    ports:
      - 8000:8000
    env_file: .env
    extra_hosts: 
      - "host.docker.internal:host-gateway"

volumes:
  static_volume:
  media_volume:
  nginx_secrets:
