version: "3.9"

services:
  stadtlueued-service-database:
    container_name: stadtlueued-service-database
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres -d postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:14-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: stadtlueued-service-service
    env_file: .env.local
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  stadtlueued-service-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deps
    container_name: stadtlueued-service-frontend
    image: stadtlueued-service-frontend
    env_file: ./frontend/.env.example
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm start

  stadtlueued-service-backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint.sh
    container_name: stadtlueued-service-backend
    image: stadtlueued-service-backend
    volumes:
      - .:/code
      - ../stadtlueued-service-backend-logs:/logs
    ports:
      - 8001:8001
    env_file: .env.local
    depends_on:
      - stadtlueued-service-database
