FROM node:18-alpine AS builder
WORKDIR /app
ENV NODE_ENV=production  
COPY frontend/package*.json .
RUN npm ci
COPY ./frontend .
RUN npm run build

FROM python:3.12-slim
WORKDIR /code
COPY ./requirements*.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.prod.txt 
COPY . .
COPY --from=builder /app/build frontend/build
EXPOSE 8000
ENTRYPOINT ["bash", "/code/docker-entrypoint.prod.sh"]
