services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: stadtlueued-service-nginx
    restart: unless-stopped
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - stadtlueued-service-backend

  stadtlueued-service-backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: bash /code/docker-entrypoint.prod.sh
    container_name: stadtlueued-service-backend
    image: stadtlueued-service-backend
    volumes:
      - ../stadtlueued-service-backend-logs:/logs
      - static_volume:/code/static
      - media_volume:/code/media
      - nginx_secrets:/etc/letsencrypt
    ports:
      - 8001:8001
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  static_volume:
  media_volume:
  nginx_secrets:
