version: "3.9"

services:
  portfolio-reactified-database:
    container_name: portfolio-reactified-database
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres -d postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:14-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: portfolio-reactified-service
    env_file: .env.local
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  portfolio-reactified-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deps
    container_name: portfolio-reactified-frontend
    image: portfolio-reactified-frontend
    env_file: ./frontend/.env.example
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm start

  portfolio-reactified-backend:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint.sh
    container_name: portfolio-reactified-backend
    image: portfolio-reactified-backend
    volumes:
      - .:/code
      - ../portfolio-reactified-backend-logs:/logs
    ports:
      - 8000:8000
    env_file: .env.local
    depends_on:
      - portfolio-reactified-database
